language: ruby
cache: bundler
install: bundle install --without development --deployment --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
addons:
  code_climate:
    repo_token: b3db5b7df9a0a1d0fd3503e72d7431ffbfa172492c2840d590ccb2fafd9172d3 
rvm:
  - 2.1.3
env:
  - MYSQL_USERNAME=travis APP_SECRET=2d3a08dfea079fe45bcb7f830b010eda
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec
