language: ruby
bundler_args: --jobs=3 --retry=3
cache:
  bundler: true
addons:
  code_climate:
    repo_token: b3db5b7df9a0a1d0fd3503e72d7431ffbfa172492c2840d590ccb2fafd9172d3 
rvm:
  - 2.1.3
env:
  - MYSQL_USERNAME=travis APP_SECRET=2d3a08dfea079fe45bcb7f830b010eda
before_script:
  - export DISPLAY=:99.0
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:test:prepare
  - RAILS_ENV=test xvfb-run --server-args="-screen 0 1280x1024x24" bundle exec rspec spec
