version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        buildno: 1
    volumes:
     - ".:/var/www/"
    ports:
     - "4000:4000"
    links:
     - db
     - memcached
  #    - redis
  db:
    # Debug
    #    command: bash 
    #tty: true
    command: mysqld_safe --skip-grant-tables
    image: mariadb:latest
    volumes:
     - "./db_data:/var/lib/mysql"
     - "./ext/mysql.conf.d:/etc/mysql/conf.d"
    environment:
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_USERNAME
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
     - MYSQL_ROOT_HOST
  memcached:
    image: memcached:latest
  #redis:
  #  image: redis
