version: "3"

services:
  web:
    image: ensl/ensl.org:latest
    volumes:
     - "../public:/var/www/public"
     - "../logs:/var/www/log"
    ports:
     - "4000:4000"
    depends_on:
     - db
     - memcached
     - smtp
  #    - redis
  db:
    image: mariadb:latest
    command: mysqld
    volumes:
     - "./db_data:/var/lib/mysql"
     - "./ext/mysql.conf.d:/etc/mysql/conf.d"
    environment:
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_USERNAME
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
#     - MYSQL_ROOT_HOST
  memcached:
    image: memcached:latest
  smtp:
    image: mwader/postfix-relay:latest
    restart: always
    volumes:
     - "../dkim:/etc/opendkim/keys"
    environment:
      - POSTFIX_myhostname=ensl.org
      - OPENDKIM_DOMAINS=ensl.org
  #redis:
  #  image: redis
