development:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] %>