development:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] || SecureRandom.alphanumeric(32) %>

test:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] || SecureRandom.alphanumeric(32) %>

production:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] || SecureRandom.alphanumeric(32) %>

staging:
  secret_key_base: <%= ENV["APP_SECRET_KEY_BASE"] || SecureRandom.alphanumeric(32) %>