development:
  secret_token: <%= ENV["APP_SECRET"] %>

test:
  secret_token: <%= ENV["APP_SECRET"] %>

production:
  secret_token: <%= ENV["APP_SECRET"] %>

staging:
  secret_token: <%= ENV["APP_SECRET"] %>
