default: &default
  toolbar:
      - styleselect | bold italic | undo redo
      - image | link
  plugins:
    - image
    - link

articles:
  <<: *default
#  mode: "textareas",
  #theme: "modern"
  plugins: 
    - inlinepopups
    - contextmenu
    - nonbreaking
    - template
#  theme_advanced_buttons1: "bold,italic,blockquote,|,bullist,numlist,|,formatselect,|,link,unlink,image,|,cleanup,code",
#  theme_advanced_buttons2: "",
#  theme_advanced_buttons3: "",
#  theme_advanced_buttons4: "",
  convert_urls: false,
#  content_css: '<%= asset_path "application.css"