#!/usr/bin/env ruby

require 'rack/handler'
Rack::Handler::WEBrick = Rack::Handler.get(:puma)

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
